["priority: critical"]
color = "b60205"
name = "priority: critical"
description = "This should be dealt with ASAP. Not fixing this issue would be a serious error."

["priority: high"]
color = "d93f0b"
name = "priority: high"
description = "After critical issues are fixed, these should be dealt with before any further issues."

["priority: low"]
color = "0e8a16"
name = "priority: low"
description = "This issue can probably be picked up by anyone looking to contribute to the project, as an entry fix"

["priority: medium"]
color = "fbca04"
name = "priority: medium"
description = "This issue may be useful, and needs some attention."

["type: skip ci"]
color = "FCBA1F"
name = "type: skip ci"
description = "Skips CI checks"

["type: performance"]
color = "6572A4"
name = "type: performance"
description = ""

["status: abandoned"]
color = "fc9580"
name = "status: abandoned"
description = "It's believed that this issue is no longer important to the requestor and no one else has shown an i"

["status: accepted"]
color = "d66039"
name = "status: accepted"
description = "It's clear what the subject of the issue is about, and what the resolution should be."

["status: available"]
color = "fcefa6"
name = "status: available"
description = "No one has claimed responsibility for resolving this issue."

["status: blocked"]
color = "ffcc9e"
name = "status: blocked"
description = "There is another issue that needs to be resolved first, or a specific person is required to comment"

["status: completed"]
color = "250077"
name = "status: completed"
description = "Nothing further to be done with this issue."

["status: in progress"]
color = "f4c9a1"
name = "status: in progress"
description = "This issue is being worked on"

["status: on hold"]
color = "c8a2f9"
name = "status: on hold"
description = "Similar to blocked, but is assigned to someone"

["status: review needed"]
color = "e99695"
name = "status: review needed"
description = "The issue has a PR attached to it which needs to be reviewed."

["type: breaking"]
color = "d6a30c"
name = "type: breaking"
description = ""

["type: bug"]
color = "d73a4a"
name = "type: bug"
description = "Something isn't working"

["type: dependencies"]
color = "0366d6"
name = "type: dependencies"
description = "Pull requests that update a dependency file"

["type: deprecated"]
color = "2e0baa"
name = "type: deprecated"
description = ""

["type: docs"]
color = "0075ca"
name = "type: docs"
description = "Improvements or additions to documentation"

["type: duplicate"]
color = "cfd3d7"
name = "type: duplicate"
description = "This issue or pull request already exists"

["type: feature"]
color = "a2eeef"
name = "type: feature"
description = "New feature or request"

["type: help wanted"]
color = "008672"
name = "type: help wanted"
description = "Extra attention is needed"

["type: invalid"]
color = "e4e669"
name = "type: invalid"
description = "This doesn't seem right"

["type: maintenance"]
color = "c2e0c6"
name = "type: maintenance"
description = ""

["type: question"]
color = "d876e3"
name = "type: question"
description = "Further information is requested"

["type: security"]
color = "7dede7"
name = "type: security"
description = "Pull requests that address a security vulnerability"

["type: tests"]
color = "F25F44"
name = "type: tests"
description = ""

["type: wontfix"]
color = "ffffff"
name = "type: wontfix"
description = "This will not be worked on"

["type: ui/ux"]
color = "5319E7"
name = "type: ui/ux"
description = "UI/UX design"
