name: Assign PR to creator

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

# This ensures that previous jobs for the workflow are canceled when the ref is
# updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  assign-author:
    runs-on: self-hosted
    steps:
      - name: Assign PR to creator
        uses: toshimaru/auto-author-assign@v1.5.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
