name: Release CI

on:
  release:
    types:
      - published
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+(-[a-zA-Z]+[0-9]+)?
    branches:
      - master

# This ensures that previous jobs for the workflow are canceled when the ref is
# updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update_release_draft:
    name: "Release Drafter"
    runs-on: misc
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "default branch"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release_notify:
    name: "Release Notifier"
    runs-on: misc
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - update_release_draft
    steps:
      - id: latest_release
        uses: thebritican/fetch-latest-release@v2.0.0
      - uses: dawidd6/action-send-mail@v3.6.1
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: ${{ github.repository }} release is out!
          convert_markdown: true
          html_body: |
            # Release ${{ steps.latest_release.outputs.tag_name }}

            ***

            ${{ steps.latest_release.outputs.body }}
          to: ${{ secrets.MAIL_TO }}
          from: OmsBot
